version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile

    image: badlight_local_postgres

    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups

    env_file:
      - ./.envs/.local/.postgres

  flask:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile

    image: badlight_local_flask

    volumes:
      - ./badlight:/badlight
      - ./tests:/tests

    env_file:
      - ./.envs/.local/.flask
      - ./.envs/.local/.postgres

    ports:
      - "5000:5000"

    depends_on:
      - postgres

    command: /start
