"""empty message

Revision ID: 1a54385c7d8c
Revises: 091ac910ea4b
Create Date: 2020-04-28 16:55:27.604046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a54385c7d8c"
down_revision = "091ac910ea4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user", ["uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    # ### end Alembic commands ###
